[LI-HOTFIX] Stop enqueuing unnecessary LeaderAndIsrResponseReceived events
linkedin/kafka pull request #226
Opened 2021-12-09 22:30 UTC by xiowu0

TICKET = LIKAFKA-40059
LI_DESCRIPTION =

With li combined request feature, a combined response will cause the controller to enqueue an event of LeaderAndIsrResponseReceived, regardless of whether the combined request contains LeaderAndIsr Request or not.

As a result, a LI combined request with only metadata update would end up generating an empty LeaderAndIsrResponseReceived event in the controller queue when the response is received by the controller.

Since the controller may send out "metadata update requests" to all live brokers, it fills up the controller queue with empty LeaderAndIsrResponseReceived events quickly (e.g., single metadata update request can generate X LeaderAndIsrResponseReceived events in the controller queue, where X = number of live brokers in the cluster).

EXIT_CRITERIA = MANUAL ["when li combined request/response is no longer needed"]

2021-12-09 23:26 UTC, efeg commented on core/src/main/scala/kafka/controller/ControllerRequestMerger.scala
> +      && (!leaderAndIsrResponse.partitions().isEmpty() || leaderAndIsrResponse.error() != Errors.NONE)) {
Nit `isEmpty()` -> `isEmpty`

2021-12-09 23:26 UTC, efeg commented on core/src/main/scala/kafka/controller/ControllerRequestMerger.scala
> +      && (!stopReplicaResponse.partitionErrors().isEmpty()) || stopReplicaResponse.error() != Errors.NONE) {
Nit `isEmpty()` -> `isEmpty`

2021-12-10 00:02 UTC, xiowu0 commented on core/src/main/scala/kafka/controller/ControllerRequestMerger.scala
> +      && (!leaderAndIsrResponse.partitions().isEmpty() || leaderAndIsrResponse.error() != Errors.NONE)) {
fixed

2021-12-10 00:17 UTC, lmr3796 requested changes
Nit: title seemed too long and may be truncated at merge.

Suggesting this as subject/title and keep the remaining description
```
[LI-HOTFIX] Stop enqueuing unnecessary LeaderAndIsrResponseReceived
```

2021-12-10 00:38 UTC, efeg approved these changes
Noticed a few nits / typos.
Otherwise LGTM.

2021-12-10 00:38 UTC, efeg commented on core/src/test/scala/unit/kafka/controller/ControllerRequestMergerTest.scala
> +  def testNotTriggerCallbackForUpdateMetadataReqeust(): Unit = {
Typo: `Reqeust` -> `Request`

2021-12-10 00:38 UTC, efeg commented on core/src/test/scala/unit/kafka/controller/ControllerRequestMergerTest.scala
> +      new LiCombinedControlResponseData().setStopReplicaPartitionErrors(stopReplicaPartitionsError);
Nit: semicolon is unnecessary.

2021-12-10 00:38 UTC, efeg commented on core/src/test/scala/unit/kafka/controller/ControllerRequestMergerTest.scala
> +      new LiCombinedControlResponseData().setLeaderAndIsrErrorCode(Errors.UNKNOWN_SERVER_ERROR.code());
Nit: semicolon is unnecessary.

2021-12-10 00:53 UTC, lmr3796 approved these changes
+1

2021-12-10 01:30 UTC, merged